endlessm/flatpak

Makefile.am, common/flatpak-dir.c, configure.ac
This is needed as a first step to having apps installed both in the system
directory and an external location, even though for now is just one or another
but not both.
This commit defines the --with-external-install-dir configuration parameter
that allows specifying a path which is considered at runtime: if it exists,
that one will be used, otherwise the default system directory will be picked.
https://phabricator.endlessm.com/T12030
=> Allow defining and external location for the system installation and use it

debian/rules
This will make flatpak check on runtime for the existence of this directory,
and use it if it's there, falling back to /var/lib/flatpak otherwise.
https://phabricator.endlessm.com/T12030
=> Use /var/endless-extra/flatpak as external directory for system installation

Makefile.am, dbus.service.d/flatpak.conf.in, env.d/flatpak.env.in, profile/flatpak.sh.in
This will make it possible for the shell to discover exported files
installed under that location, so that the shell can find those flatpaks.
https://phabricator.endlessm.com/T13480
=> Include the external installation directory in XDG_DATA_DIRS

common/flatpak-run.c, common/flatpak-run.h, doc/flatpak-build-finish.xml, doc/flatpak-run.xml
This adds a new `multiarch` feature which allows bundling e.g. 32-bit binaries to be run in a x86_64 environment. By default, the seccomp filter is configured to allow only the native architecture. When the `multiarch` feature is enabled, the filter will be configured to allow running binaries of additional architectures supported. For x86_64, this allows x86 32-bit binaries; and for Aarch64, allows 32-bit ARM binaries.
Application bundles can use the feature e.g. in order to ship 32-bit binaries alongside with a mostly-64-bit application. This is particularly interesting when for applications that might launch themselves prebuilt programs for which 64-bit versions do not exist. For example, the Steam application is available as a 64-bit executable, but some of the games available are …
=> Support mixed (multilib/multiarch) binaries in Flatpaks

common/flatpak-dir.c
This means that the remote is there, but disabled.
This is needed for e.g. bundles without origin url, and when bundles
starting using this codepath this regressed like in:
https://github.com/flatpak/flatpak/issues/314
https://phabricator.endlessm.com/T13625
=> common: Accept empty/no url in modify_remote

common/flatpak-dir.c, system-helper/org.freedesktop.Flatpak.policy.in
Add logic in flatpak_dir_update_remote_configuration() so that the step of
configuring the local remotes after fetching the required date from the
server's summary file is performed via the system helper when present.
Also, authorize org.freedesktop.Flatpak.configure-remote via PolKit for
privileged users, so that a repo's config can be seamlessly updated from
clients, such as GNOME Software, when needed
https://phabricator.endlessm.com/T13403
=>  Integrate flatpak_dir_update_remote_configuration() with the system helper

common/flatpak-dir.c, data/org.freedesktop.Flatpak.xml, system-helper/flatpak-system-helper.c, system-helper/org.freedesktop.Flatpak.policy.in, system-helper/org.freedesktop.Flatpak.rules.in
Made it runnable by any user and hook the required additional logic
in flatpak_dir_update_remote_configuration() to get it called when
run from outside the helper itself.
https://phabricator.endlessm.com/T14167
=> New "UpdateRemote" method added to the system helper D-Bus API

common/flatpak-run.c
When no session helper is available (e.g. running flatpak run from a
socket-activated service unit), we need to be extra careful before
making these two files appear inside the sandbox. Otherwise, if they
are not reachable on the host system (or just symlinks to non-existent
targets), flatpak won't be able to create the sandbox, which will fail
due to a "No such file or directory error".
https://phabricator.endlessm.com/T14331
=> Extra checks mounting /etc/{resolv.conf|localtime} without session helper

app/flatpak-builtins-update.c
Without this, the ARM image build tries to update the GNOME runtime appstream and fails because it doesn't exist even though the runtimes for ARM do. We actually only want the appstream from the apps repo, though.
https://phabricator.endlessm.com/T14666
=> update --appstream: Actually handle remote argument if specified

Makefile.am, system-helper/flatpak-system-helper.service.in
Otherwise we can see in the log that update-mime-database will complain
about it not being set when installing an application using the system
helper.
https://phabricator.endlessm.com/T14796
=> system-helper: make sure to run with XDG_DATA_DIRS set

common/flatpak-dir.c
This will be useful when an automated builder runs the triggers
chrooted.
=> dir: make it possible to disable triggers sandbox with an env var

common/flatpak-utils.c
The download was getting stuck when launched from within a thread as is
the case when using GNOME Software.
This patch simplifies the code that downloads the extra data and drops
the use of a mainloop, calling the libsoup related code synchronously
instead. It also now returns an error when an issue occurred while the
data was being downloaded.
https://phabricator.endlessm.com/T14824
=> Fix downloading extra data in libflatpak

common/flatpak-dir.c
Since the problems with running bubblewrap in the image builder have been figured out, there's no reason to allow disabling the trigger sandboxing via environment variable.
https://phabricator.endlessm.com/T14860
=> Revert sandboxed trigger changes

debian/control
flatpak-builder tries to run appstream-compose from the host when
finishing builds. Add a dependency on appstream-util to supply it.
https://phabricator.endlessm.com/T14935
=> Require appstream-util for flatpak-builder

common/flatpak-dir.c
It turns out that flatpak_dir_remote_fetch_summary can return TRUE,
yet leave summary_bytes NULL. The code further down does not deal
gracefully with summary_bytes being NULL, so error out early instead
of crashing.
https://phabricator.endlessm.com/T15125
=> Avoid a crash during update --appstream

common/flatpak-run.c
It turns out that it is impossible for to get ptrace capabilities
for child user namespaces in the current kernel if the user
namespace is created as root, which is what happens when bwrap
is setuid root (see https://github.com/flatpak/flatpak/issues/557
for details).
This is very problematic, as ptrace rights controls access to
/proc/$pid/root which is what we base the detection of peer
app id and rights on for portals.
For now, we disable user namespaces (except for the case of
unprivileged user namespaces, where it is necessary and works).
https://phabricator.endlessm.com/T15430
=> Don't user user namespaces when bubblewrap is setuid

common/flatpak-utils.c
So far, the installation of external apps can only be cancelled
before flatpak starts downloading the extra data, as there's no
cancellable being passed to g_input_stream_read_async().
This fixes that problem, making it possible to cancel installs
from GNOME Software regardless of the installation stage.
https://phabricator.endlessm.com/T15568
=> Allow cancelling the downloading process for extra data

common/flatpak-dir.c
There was a bug in this code that was causing trouble because the remove D-Bus
call to update-remote was returning successfully but the code was still running
through flatpak_dir_modify_remote() even in that case, causing the PolKit auth
dialog to show up, as configure-remote requires authentication.
This was hard to reproduce as it would only happen in situations when the remote
contained a value for a supported parameter (either title or default-branch) in
the server's summary file, as it was the case in the Endless Coding image the first
time it booted, because it would try to update the 'eos' repository's title to the
one in the summary file, and that would only happen once.
This patch makes sure that we either use the update-remote method (when using the
system helper) or the …
=> Return right after having executed the UpdateRemote command via the system helper

lib/flatpak-installation.c
As a temporary workaround for the progress report
issue, add a whitelist of apps that has extra-data
and use that to detect extra-data apps.
This is meant to be a temporary downstream solution
until a proper fix lands upstream.
https://phabricator.endlessm.com/T15603
=> Whitelist apps with extra-data

Makefile.am
Since Glnx uses forloop initial declarations, it should
be compiled with at c11 or c99.
https://phabricator.endlessm.com/T17345
=> project: Compile libglnx with -std=c11

common/flatpak-dir.c
For Endless, desktop search is an important feature that we need
to enable by default, especially for Endless content apps.
This reverts commit 2ebf67286660f5111baac379fd44a401f57b40bb.
Note that the revert could not be applied cleanly due to later
commits.  In particular, note that the handling of the new_name
variable should not be reverted.
https://phabricator.endlessm.com/T18082
=> Revert "Disable exported search providers by default"

common/flatpak-dir.c
This reverts commit 4e3767fabff9b960c11e0ea201c7351fcfb36bd9. The
initial upstream review feedback on this patch is that it might
accidentally delete your repo sometimes. Doesn't seem wise to
ship the WIP until that's fixed.
https://phabricator.endlessm.com/T15391
=> Revert "Remove cache directory when install runs out of disk"

app/flatpak-builtins-add-remote.c
Resolver errors are more likely in offline remote adds than IO
errors. Catch them first when we're downgrading metadata update
errors to a warning.
https://phabricator.endlessm.com/T17172
=> remote-add: also ignore resolver errors

common/flatpak-dir.c
In case the summary file is GPG-signed, we already have other better
ways of verifying expectations around the installed ref.
If the deployed branch does not match xa.ref, simply warn instead of
aborting.
Based on a patch by Dan Nicholson <nicholson@endlessm.com>
https://phabricator.endlessm.com/T17772
=> dir: relax requirements around xa.ref matching deployed commit

common/flatpak-utils.c
When building the ostree-metadata branch (which only happens when
configured with --enable-p2p), we are supposed to create empty commits
which contain only metadata. However, the code to do this was wrong, and
was instead pulling in all the files from the current working directory
and committing them.
Fix that code to actually create an empty commit.
This could have been a fairly serious bug were it not for the fact that
nobody’s using this code because it’s all experimental.
Spotted as part of https://github.com/ostreedev/ostree/pull/1158.
Closes: #1066
Approved by: alexlarsson
---
This isn’t attached to a particular task; just a recent upstream fix which I really think we ought to have.
=> common: Don’t commit arbitrary files into the ostree-metadata branch

common/flatpak-dir.c
If there is an unmainted extension already installed for an extension
point, lets use it instead of downloading from the remote.
https://phabricator.endlessm.com/T19169
=> dir: Prefer unmaintained related extensions

app/flatpak-builtins-ls-remote.c
The code assumes that *all* refs in a remote contain a slash, which
technically is not the case, and pragmatically is definitely not the
case once the remote has an ostree-metadata ref.
Rebase 0.9.8.8: Affected code block has moved slightly from upstream.
https://phabricator.endlessm.com/T19867
=> ls-remote: Fix crash when ostree-metadata ref exists in remote

debian/.gitignore, debian/autogen.sh, debian/changelog, debian/control, debian/copyright, debian/flatpak-builder.install, debian/flatpak.examples, debian/flatpak.install, debian/flatpak.postinst, debian/gbp.conf, debian/libflatpak-doc.install, debian/libflatpak-doc.links, debian/libflatpak-doc.maintscript, debian/libflatpak0.symbols, debian/rules, debian/test.sh, debian/tests/builder, debian/tests/builder-python, debian/tests/control, debian/tests/gnome-desktop-testing, debian/watch
flatpak (0.10.1-0endless0) unstable; urgency=medium
* New upstream release
- Adds appstream-glib as a dependency
- Drop some upstreamed Endless patches for config file monitoring
-- Philip Withnall <withnall@endlessm.com>  Fri, 24 Nov 2017 15:10:00 +0000
flatpak (0.10.0-2endless0) unstable; urgency=medium
* Update Debian packaging from Sid
- This splits flatpak-builder out into a separate package
- Change dh_missing --fail-missing to --list-missing until we have
debhelper 10.6, as 10.5 does not know about .examples files (which
flatpak packaging uses): we should expect only flatpak-bisect to be
listed as missing
* Rebase existing Endless patches
-- Philip Withnall <withnall@endlessm.com>  Wed, 22 Nov 2017 18:00:00 +0000
https://phabricator.endlessm.com/T20056
---
Code branch: …
=> Update to 0.10.1 (Debian)

common/flatpak-dir.c
Reinstate the upstream functionality that search provider .ini files should be rewritten on export to add the DefaultDisable key, but add an exception so that apps from com.endlessm.* are not rewritten. This allowing us to control the default search providers on our own apps, but uses the more secure default configuration for third-party apps.
https://phabricator.endlessm.com/T18132
=> T18132: default to disable search providers fron non-Endless apps

debian/changelog, debian/libflatpak0.symbols
This release has the needed changes to support listing temporary
remotes, as well as setting the correct URL in the remote.
https://phabricator.endlessm.com/T20078
=> New build release 0.10.1-1endless1

lib/flatpak-installation.c
Mark subpaths as a NULL terminated array. Without this the GIR makes
this a single utf8 parameter and bindings can't use it.
https://phabricator.endlessm.com/T18667
=> lib/installation: Fix install/update_full() subpaths annotation

common/flatpak-dir.c, common/flatpak-utils.c
Here’s a potential fix for the crash in https://phabricator.endlessm.com/T20861. I haven’t tested it other than with compilation, since I’m not sure of the reproduction conditions.
The main fix is the second patch, which I’ve submitted upstream as https://github.com/flatpak/flatpak/pull/1361. The first patch (fix division by zero) is unrelated, but looks like a useful one to have.
https://phabricator.endlessm.com/T20861
=> T20861 Potential fix for OstreeAsyncProgress crash

app/flatpak-builtins-build-export.c, app/flatpak-builtins-info-remote.c, app/flatpak-builtins-info.c, app/flatpak-builtins-ls-remote.c, common/flatpak-dir.c, common/flatpak-dir.h, common/flatpak-utils.c
This is a backport of some upstream commits needed for T20759 along with some other harmless changes. The only one that didn't apply cleanly was 0c52d55ea37b1cc0d30455777f6cb2418d2c79f3 and that ended up being a no-op, so this should be a straightforward merge.
https://phabricator.endlessm.com/T20759
=> Backport some commits from flatpak 0.11

app/flatpak-builtins-run.c
This isn't needed for servers and starting the a11y bus on a
fresh session bus takes upwards of 15 seconds.
Fixes #1471
Closes: #1486
Approved by: alexlarsson
(cherry-pick from upstream, drop on rebase)
https://phabricator.endlessm.com/T21429
=> run: Add option to disallow a11y bus proxying (cherrypick)

lib/flatpak-installation.c
In list_remotes_for_configured_remote(), we call
ostree_repo_finder_avahi_start() without checking the error status. This
means the OstreeRepoFinderAvahi instance passed to
ostree_repo_find_remotes_async() could be in an error state, which leads
to flatpak getting infinitely stuck waiting for the result of that
operation. So this commit removes the OstreeRepoFinderAvahi instance
from the array if it failed to start, and returns early if only LAN
remotes were requested. This is also consistent with how ostree itself
handles an error starting the Avahi finder instance in case NULL is
passed to ostree_repo_find_remotes_async() instead of a finders array.
This error condition happens on the Endless OBS server because there's
no Avahi daemon in the chroot used to run "make check".
=> lib: Properly handle missing Avahi daemon

tests/testlibrary.c
The GFileMonitor returned by flatpak_installation_create_monitor() is
already tested in test_install_launch_uninstall(), so there's not much
point in testing it again in test_list_updates, and for some reason it
is causing a test failure on OBS.
=> tests: Limit use of installation monitor

lib/flatpak-installation.c
When getting the dynamic remotes for the installed refs, if no refs
with a collection ID are found, then the ostree_repo_find_remotes_async
function early returns and thus it would result in an infinite loop in
flatpak_installation_list_installed_refs_for_update.
This patch only tries to find the dynamic remotes when there are such
refs, thus preventing the mentioned error and any extra unnecessary
processing.
https://phabricator.endlessm.com/T22125
=> lib/installation: Don't try to find dynamic remotes when not needed

configure.ac
This commits makes `--enable-p2p` default to yes rather than no, so that
the CI uses it when running tests (since we already use it for the
version of flatpak that goes into Endless). This also has the effect of
making it easier for people who build Flatpak to have a version closer
to what goes into the OS.
=> Enable P2P by default

lib/flatpak-remote-ref.c
In flatpak_remote_ref_new(), the state parameter is optional, so check
if it's NULL before trying to use it in
flatpak_remote_state_lookup_sparse_cache(). This prevents a seg fault
when GNOME Software is installing a .flatpakref file.
Fixes https://github.com/flatpak/flatpak/issues/1632
=> lib: Don't try to use a NULL FlatpakRemoteState

common/flatpak-dir.c
We should not require a collection ID to be set for this to actually be
optional.
Doing so will make us require a network connection for flaptak installs
and updates even in case we already have the requested ref available,
for instance because it has been previously pulled by a different process,
as it's the case during an Endless OS update that also involves
updating or installing applications.
https://phabricator.endlessm.com/T22362
=> flatpak-dir: make optional summary really optional

common/flatpak-dir.c, common/flatpak-dir.h
On some code paths, flatpak_dir_get_remote_state_optional() is used so
summary fetch errors and metadata fetch errors are treated as non-fatal,
and later flatpak_remote_state_ensure_summary() or
flatpak_remote_state_ensure_metadata() is used, which gives a pretty
unhelpful error message. So this commit saves the error from a failed
summary or metadata fetch into the FlatpakRemoteState object and prints
the message when the flatpak_remote_state_ensure_* function is called to
make that error message more specific and useful.
This also means that the "fail with missing gpg key" unit test in
test-repo.sh is working again. It was broken by the last commit ("dir:
make optional summary really optional) which caused the install
operation in that test to fail later than before with a different …
=> dir: Save error messages from summary/metadata fetches

lib/flatpak-installation.c
Since the remote metadata can come from either the summary file or the
ostree-metadata ref, and the latter is available offline, there's no
reason to require the summary file when fetching metadata. This commit
changes flatpak_installation_fetch_remote_metadata_sync() and
flatpak_installation_fetch_remote_size_sync() to treat summary fetch
errors as non-fatal. Treating them as fatal is currently preventing
GNOME Software from doing LAN app updates.
GNOME Software should ideally be using metadata from the commits
themselves, but that change will have to wait for the fix for
https://github.com/flatpak/flatpak/issues/1592, I think.
=> lib: Make the summary optional when fetching metadata

common/flatpak-dir.c
The pop was missing, meaning that calling flatpak_dir_find_latest_rev()
corrupted the thread default main context stack of the caller.
=> common: Pop the thread default main context in find_latest_rev()

common/flatpak-dir.c
There is no need to force a fsync after pulling into the child repo,
because we will anyway copy/verify it into the system repo. It is
never used for stable storage.
This makes system installation faster.
Closes: #1808
Approved by: alexlarsson
(cherry picked from commit 9901ce875fc88db49ec3f6e72ffa850ab3d22ac9)
Signed-off-by: Robert McQueen <rob@endlessm.com>
https://phabricator.endlessm.com/T23081
=> dir: Never fsync child repos

profile/flatpak.sh.in
Add the com.id.foo wrappers which are created by flatpak in the
export/bin dir to the default PATH.
https://phabricator.endlessm.com/T22334
=> profile/flatpak.sh.in: add export/bin dirs to PATH

common/flatpak-dir.c
Recently, we ported flatpak's logic to disable min-free-space-percent=0
to min-free-space-size but at that stage only one of the config option
was allowed to be mentioned in the config by ostree.
Recent ostree release now support co-existing of both options therefore,
flatpak should consider the co-existence and re-write the config
accordingly. Config is re-written in case of:
1) It has min-free-space-percent=0 only. (That is probably from the
previous re-writes).
2) If there are no min-free-space-* options.
Other than that, the config remains unchanged and the co-existence
of these options is governed by ostree.
https://phabricator.endlessm.com/T23379
=> common/dir: Consider co-existence of min-free-space-* options

common/flatpak-installation.c
Flatpak has API called flatpak_installation_list_remotes_by_type() which
can list dynamic (LAN/USB) remotes that mirror configured remotes in an
installation. It does this by searching them for the appstream/<arch>
ref, such as appstream/x86_64. But Flatpak now supports
appstream2/<arch> as a way to provide the appstream data as uncompressed
XML, and it's possible that a USB created with `flatpak create-usb` (or
a LAN peer) only has the appstream2 ref available for a certain
collection ID. So this commit changes
list_remotes_for_configured_remote() so that it looks for both
appstream/<arch> and appstream2/<arch>, which makes
flatpak_installation_list_remotes_by_type() robust to that scenario.
=> common/installation: Search dynamic remotes for appstream2 also

system-helper/flatpak-system-helper.service.in
Our benchmarks show this significantly reduces the interactivity impact of
ongoing Flatpak operations while the user is continuing other tasks on the
system. The effect is very pronounced with the default CFQ scheduler, and in
combination with BFQ, using the idle class improves the worst case to nearly
the same as an unloaded system.
https://phabricator.endlessm.com/T22479
=> system-helper: set IO class to idle

common/flatpak-dir-private.h, common/flatpak-dir.c, common/flatpak-run.c
flatpak run checks if there is any previous-ids for the app and
sees if there is a corresponding app-dir in ~/.var/app/ .
If so, it renames that app-dir to the new app-id and provides
a symlink from old app-id dir to new app-id dir. The symlink is
needed because even though the XDG_DATA_DIR and other environment
variables are set to the new ID by flatpak run, the app itself
could've stored (eg in GSettings, or other files) paths which
contained the old ID.
https://phabricator.endlessm.com/T23532
=> RFC: Support migration from old app-ids to new app-id

common/flatpak-dir.c, tests/make-test-app.sh, tests/testlibrary.c
When migrating an installed app from eos-apps to Flathub, it may have had a
different app ID (com.example.App) in eos-apps to the Flathub ID
(net.example.app). The migration logic arranges for previous-ids to be set
in the deploy file, and flatpak-dir.c preserves this across app updates.
A user may have the app on their desktop or pinned to the taskbar under its
old ID, and the Shell uses X-Flatpak-RenamedFrom to update these to the new
ID. The migration logic arranges for the old ID to be added to
X-Flatpak-RenamedFrom at migration time; we need to also preserve this
across app updates.
Note that the Flathub version of the app may well have its own entries in
X-Flatpak-RenamedFrom. It is unlikely that these will overlap with ours,
but for neatness we take care to avoid adding duplicates. …
=> Add previous-ids to exported .desktop files

app/flatpak-builtins-create-usb.c
This commit removes the call to flatpak_dir_update_summary() in the
create-usb implementation. It turns out that libostree does not rely on
a summary being present when a pull is local (meaning it uses a file://
URI). I'm not sure where I got the idea that create-usb depends on a
summary in the source repo. I went back to the first commit that
introduced the "ostree create-usb" command and even using that a summary
isn't required, so it seems unlikely that this changed recently.
One important benefit of removing the summary update is that currently
summary generation takes an exclusive lock, and we've seen on Endless
the attempt to acquire that lock time out (possibly due to a prune
happening in another process).
We could also remove the system-helper method UpdateSummary since it
doesn't …
=> create-usb: Avoid updating the source repo summary

common/flatpak-installation.c
Currently, if flatpak_installed_ref_get_latest_commit() returns NULL
(which means the ref doesn't exist in the local repo) we assume any
remote commit could be an update in
flatpak_installation_list_installed_refs_for_update() when a collection
ID is not configured on the remote. When a collection ID is configured,
if get_latest_commit() returns NULL it causes a crash in
ostree_repo_load_commit(). So this commit prevents the crash and makes
the behavior in the post-collection-id world consistent with the
behavior in the pre-collection-id world.
It's difficult to write a test for this that's not contrived, without
knowing what circumstances led to the disappearance of the ref from the
repo.
Fixes https://github.com/flatpak/flatpak/issues/2216
Closes: #2229
Approved by: alexlarsson
=> common: Don't seg fault if a ref doesn't exist

debian/changelog, debian/control
https://phabricator.endlessm.com/T24020
See https://github.com/endlessm/flatpak/pull/128 for the master changes.
=> flatpak-run: Add parental controls support for filtering apps (Debian changes)

common/flatpak-dir.c
This is independent from the app-install polkit action, which determines
whether an unprivileged user may install an app system-wide. Being
stored in accountsservice, the new boolean is also easier to set
per-user without having to programmatically write a polkit JS policy
file which handles multiple users (and parse it back again).
It overrides the OARS values.
https://phabricator.endlessm.com/T24457
=> dir: Allow app filter to disallow app installation entirely

debian/control
We need epc_app_filter_is_user_installation_allowed().
https://phabricator.endlessm.com/T24457
=> debian: Bump eos-parental-controls-0 dependency for new symbols

common/flatpak-common-types-private.h, common/flatpak-dir.c, common/flatpak-run.c
Upstream commit message:
> Don't expose /proc when running apply_extra
> 
> As shown by CVE-2019-5736, it is sometimes possible for the sandbox
> app to access outside files using /proc/self/exe. This is not
> typically an issue for flatpak as the sandbox runs as the user which
> has no permissions to e.g. modify the host files.
> 
> However, when installing apps using extra-data into the system repo
> we *do* actually run a sandbox as root. So, in this case we disable mounting
> /proc in the sandbox, which will neuter attacks like this.
https://phabricator.endlessm.com/T25408
=> Backport security fix from Flatpak 1.2.3

common/flatpak-common-types-private.h, common/flatpak-dir.c, common/flatpak-run.c
Upstream commit message:
> Don't expose /proc when running apply_extra
> 
> As shown by CVE-2019-5736, it is sometimes possible for the sandbox
> app to access outside files using /proc/self/exe. This is not
> typically an issue for flatpak as the sandbox runs as the user which
> has no permissions to e.g. modify the host files.
> 
> However, when installing apps using extra-data into the system repo
> we *do* actually run a sandbox as root. So, in this case we disable mounting
> /proc in the sandbox, which will neuter attacks like this.
Modified to fix a minor conflict in the FlatpakRunFlags hunk due to FLATPAK_RUN_FLAG_CANBUS not being present in our 1.0.x branch. This is the eos3.5 counterpart to https://github.com/endlessm/flatpak/pull/148.
https://phabricator.endlessm.com/T25408
=> Backport security fix from Flatpak 1.0.7

common/flatpak-run.c
https://phabricator.endlessm.com/T26064
=> Backport fix for CVE-2019-10063

app/flatpak-builtins-install.c, app/flatpak-builtins-list.c, app/flatpak-builtins-remote-add.c, app/flatpak-builtins-utils.c, app/flatpak-builtins-utils.h, app/flatpak-cli-transaction.c, common/flatpak-context.c, common/flatpak-dir.c, common/flatpak-run.c, common/flatpak-transaction.c, common/flatpak-utils-http.c, common/flatpak-utils-private.h, common/flatpak-utils.c, doc/flatpak-install.xml, tests/httpcache.c, tests/test-repo.sh, tests/testlibrary.c
These are cherry-picks of upstream patches from between 1.2.3 and 1.3.1 which are each either important or trivial and not risky. The only merge conflicts were trivial and are noted in the commit messages.
https://phabricator.endlessm.com/T26065
=> Backports from 1.3.1

common/flatpak-dir.c
As written, the error message would have no space or punctuation between
the extra-data path and the existing message. Other calls to
g_propagate_prefixed_error() added in
45a2eaf8a815f1647c4c36da29bd4e85d80e0f6d are fine.
https://phabricator.endlessm.com/T23928
=> common: include ": " between prefix and existing message

debian/changelog, debian/control
Depends on https://github.com/endlessm/flatpak/pull/165.
https://phabricator.endlessm.com/T27009
=> Bump libmalcontent-0-dev min requirement to 0.4.0

tests/testlibrary.c
The issue was introduced with recent changes made to GLib[1]
where invoking g_test_dbus_down() will fail after a
timeout if the GDBusConnection object for the session bus leaks.
Lets disable these tests for now until the leaks are fixed.
[1] https://gitlab.gnome.org/GNOME/glib/merge_requests/963
https://phabricator.endlessm.com/T27345
=> tests: Temporarily disable failing tests due to recent GLib changes

system-helper/org.freedesktop.Flatpak.rules.in
In 42563c5273a, we applied parental controls to administrators too,
but forgot to take into account the polkit rule change that is needed
to retain the default behaviour for app-installation for admins.
Admins historically, were able to install apps without a polkit
challenge (i.e. without requiring additional authorization for
system repo installation).
This commit brings back the default behavior for admin users, being
able to install to system repo without a polkit challenge.
During next rebase, this commit can be squashed with 42563c5273a.
https://phabricator.endlessm.com/T26968
=> polkit: Admins should always be allowed to install to system repo

tests/testlibrary.c
The changes to dconf to fix the test failures are now merged upstream[1]. Lets re-enable the tests.
This change depends on the new dconf package. Current OBS MR at https://obs-master.endlessm-sf.com/request/show/20486.
Once this lands we need to backport both this change and push the updated dconf package to 3.6.
https://phabricator.endlessm.com/T27345
[1] https://gitlab.gnome.org/GNOME/dconf/merge_requests/51
=> Revert "tests: Temporarily disable failing tests due to recent GLib changes"

common/flatpak-dir.c
The image builder doesn't have the system bus available which is required to
run the parental controls checks, so lets skip it if the
FLATPAK_SKIP_PARENTAL_CONTROLS_NO_SYSTEM_BUS env variable is set (set by the builder)
and system bus is not available.
https://phabricator.endlessm.com/T27896
=> common/dir: Skip parental controls checks when running from the eos-image-builder

NEWS, configure.ac, po/cs.po, po/da.po, po/de.po, po/es.po, po/gl.po, po/hu.po, po/id.po, po/pl.po, po/pt_BR.po, po/ru.po, po/sk.po, po/sv.po, po/tr.po, po/uk.po, po/zh_TW.po
Reporting a made-up version number risks breaking compatibility with Flatpaks that have the require-version metadata field set. Merge the 1.4.3 branch into ours (a functional no-op - the line numbers in the .po files changed) guaranteeing we are compatible, and set the extra version so we have 1.4.3.99 showing that we are ahead somehow. The require-version checks only use major/minor/micro, so we can set extra version safely.
https://phabricator.endlessm.com/T28026
=> T28026: merge in 1.4.3 and set version to 1.4.3.99

common/flatpak-transaction.c, tests/testlibrary.c
This ensures that when the operation to install the app completes, the
app is ready to run — rather than having to wait for subsequent
operations to install extensions which the app depends on (such as
content, or locales).
This fits in with the current ordering for *un*installing apps, where
the main app is uninstalled first, followed by its extensions.
https://github.com/flatpak/flatpak/issues/3017
https://phabricator.endlessm.com/T28031
=> transaction: Install extensions before apps

app/flatpak-builtins-config.c, common/flatpak-dir-private.h, common/flatpak-dir.c, common/flatpak-installation.c, common/flatpak-installation.h, doc/flatpak-config.xml, tests/testlibrary.c
In order to configure gnome-software to show specific apps in one region
without showing to all language speakers, we allow the storage of full
locales on the extra-languages key. However, these locales are ignored when
calling flatpak_installation_get_default_languages, so locales will be reduced
to their language identifier (eg. en_IN locale will be returned as 'en', and
az_Latn_AZ will be returned as 'az'). In order to get the full locales, we can
call flatpak_installation_get_default_locales instead, which can return languages
and locales.
(cherry picked from commit 65912f27fe1f2300819ece27fbeb4e2095bbdfd3)
=> app: Allow locales to be stored in the extra-languages key

debian/changelog, debian/control
**Do not merge** — it needs to be pushed manually.
Code changes in #192.
https://phabricator.endlessm.com/T28028
=> T28028 flatpak 1.5.0 rebase (Debian packaging)

app/flatpak-builtins-config.c, common/flatpak-dir.c, common/flatpak-installation.c, doc/flatpak-config.xml, tests/testlibrary.c
Trivial backport of https://github.com/flatpak/flatpak/pull/3194 from upstream.
https://phabricator.endlessm.com/T28335
=> T28335 Backport locale parsing changes from #3194

common/flatpak-parental-controls.c
Fix the following warning:
common/flatpak-parental-controls.c: In function ‘flatpak_oars_check_rating’:
common/flatpak-parental-controls.c:121:10: warning: ‘appdata_value’ may be used uninitialized in this function [-Wmaybe-uninitialized]
if (appdata_value != NULL)
^
Upstream PR: https://github.com/flatpak/flatpak/pull/3210
=> flatpak-parental-controls: Properly initialize appdata_value when checking oars rating

common/flatpak-dir.c, common/flatpak-utils-private.h, common/flatpak-utils.c
It's a common idiom in this codebase to push a temporary GMainContext as
the thread default context in order to run an async operation as if it
were sync. If we are not expecting progress callbacks this isn't a
problem, but it becomes a problem if we pass in an OstreeAsyncProgress
object that was created under a different GMainContext. The reason for
this is that OstreeAsyncProgress creates an idle source and attaches it
to the thread default context, so if we are iterating a temporary
context then the OstreeAsyncProgress's context never gets iterated, and
so no progress signals are fired.
To fix this, we introduce flatpak_progress_chain() and a RAII helper
OstreeAsyncProgressChained which creates a new OstreeAsyncProgress under
the temporary GMainContext, but forwards all its state and …
=> utils: Allow chaining OstreeAsyncProgress when pushing GMainContext

tests/Makefile.am.inc
Files in the srcdir need to be explicitly prefixed as such in rule
commands. This fixes `make install` when installed-tests are enabled.
---
Trivial backport of commit 0975c65574ab15987247e70fa32ce88035d6850e from upstream. Can be dropped with the next upstream release.
=> build: Fix the path to some installed-tests files

common/flatpak-dir.c, tests/make-test-app.sh, tests/test-run.sh
Currently we filter by app IDs to determine which search providers to enable, which means Hack and Endless Network knowledge apps are not searchable by default. Revert this patch, and instead check the BusName of search provider .ini files which are exported, and do not disable those where the search provider is from com.endlessm, so that all knowledge apps are searchable by default.
https://phabricator.endlessm.com/T28819
=> T28819: enable search based on the provider bus name, not the app ID

common/flatpak-utils.c
In flatpak-builtins-build-commit-from.c we call flatpak_repo_collect_sizes()
without initializing the passed in download size to zero, which mean
we sum with sizes with some random value as the start.
This is fixed by having flatpak_repo_collect_sizes() always initialize
the counters to 0 at the start.
Fixes https://github.com/flatpak/flatpak/issues/3362
(cherry picked from commit 3c6c51f46b753934cff9649c0937ead9c16524d3)
--------
See https://github.com/flatpak/flatpak/issues/3362 issue
The backport is necessary so that the bug doesn't manifest in our infra. @mwleeds pointed that we use our own fork of flatpak in some parts of the infrastructure. 
--------
Relevant discussions (for reference):
```
<uajain> Curious question : The fix https://github.com/flatpak/flatpak/pull/3369/files seems …
```
=> build-commit-from: Fix generation of download-size

common/flatpak-installation.c
Cache remote state so that each remote is only queried once
for getting its state.
Follow up from https://github.com/flatpak/flatpak/pull/3204#discussion_r349642324
This can be dropped in next rebase cycle.
Backported from https://github.com/flatpak/flatpak/pull/3259
=> installation: Cache remote states while querying installed refs

common/flatpak-dir.c
This backports the necessary fixes for https://github.com/flatpak/flatpak/issues/3412. This is basically the 1.4 backport in https://github.com/flatpak/flatpak/pull/3415 except that we already have `Revert "dir: Check commit signatures before resolving a ref"` and we don't actually want `Hardcode "python2" for tests` because master is based on 1.5.0 where the tests have already moved on to python3.
https://phabricator.endlessm.com/T29334
=> Backport scratch deltas fixes

app/flatpak-builtins-build-commit-from.c, app/flatpak-builtins-build-export.c, common/flatpak-dir-private.h, common/flatpak-utils.c
We store this in the sparse cache, because we don't expect it to be
set for everything.
(cherry picked from commit 077006ecc845e46a1a42d3721a2b1ebcb5572c7d)
Conflicts:
app/flatpak-builtins-build-commit-from.c
app/flatpak-builtins-build-export.c
common/flatpak-dir-private.h
common/flatpak-utils.c
The app conflicts were from the --end-of-life-rebase option not being
present in xenial version. The common conflicts were because the `eol`
and `eolr` cache keys had been turned into macros in
2db1c6e6c4219df182e95cf14205c728456782a0, but I just kept them in their
original form since that commit was much more widespread. The important
change here is to `flatpak_repo_update` to include the token type in the
summary metadata.
https://phabricator.endlessm.com/T26579
=> Add token-type per-commit metadata key and export it to summary

debian/changelog, debian/control
https://phabricator.endlessm.com/T28742
---
Code changes in #210
=> debian: Add dependency on eos-metrics-0-dev for downstream metrics

common/flatpak-utils-http.c, tests/test-http-utils.sh
Backport of https://github.com/flatpak/flatpak/pull/3478
https://phabricator.endlessm.com/T29495
=> Retry network requests on transient errors

common/flatpak-dir-private.h, common/flatpak-dir.c, common/flatpak-installation.c, common/flatpak-transaction.c, common/flatpak-transaction.h, common/flatpak-utils-private.h, tests/Makefile.am.inc, tests/libtest.sh, tests/make-test-runtime.sh, tests/test-extensions.sh, tests/testlibrary.c
These are cherry-picks from https://github.com/flatpak/flatpak/pull/3537
There were some merge conflicts in "installation: Re-implement list_installed_refs_for_update()" but otherwise pretty uneventful.
Given the 3.8.0 schedule, I think we should merge this without waiting for upstream.
https://phabricator.endlessm.com/T28651
=> T28651 Re-implement list_installed_refs_for_update()

common/flatpak-dir.c
Currently, if you are offline and a repo on a USB drive provides an
older version of something that you have installed, that will be
presented as an available update in `flatpak update` and GNOME Software
(which uses flatpak_installation_list_installed_refs_for_update()), and
the update will then fail due to being a downgrade. Fix the issue by
checking the timestamp on a remote commit and ignoring ones older than
the local commit. For list_installed_refs_for_update() this bug is a
recent regression from the commit "installation: Re-implement
list_installed_refs_for_update()", and for the update CLI command it
might be a more long-standing bug.
This patch can't go upstream since there the use of the libostree p2p
api has been removed.
https://phabricator.endlessm.com/T28651
=> dir: Don't include downgrades in update list

common/flatpak-dir.c
In the implementation of flatpak_deploy_data_get_string() and a few
other getters, we borrow a value from a GVariant that is a child of the
main GVariant, and free the child via g_autoptr(). Since we then no
longer hold a reference to the child variant, if it is freed internally
in GLib, the borrowed value is no longer safe to access. And GLib frees
all children of a GVariant when serializing it; see the implementation
of g_variant_get_data().
Therefore, in the implementation of the list command the value returned
by flatpak_deploy_data_get_runtime() is not valid after
flatpak_deploy_data_get_origin() is called, and the end result is that
the values in the runtime column of the output are sometimes gibberish.
For now, fix it by ensuring that the GVariant for deploy data is
serialized …
=> dir: Fix memory errors in use of deploy variant

common/flatpak-dir.c, common/flatpak-run.c, configure.ac
We'd like to use the same flatpak on our infrastructure so that it
captures any Endless deviations such as handling of search providers.
However, eosmetrics isn't available on our Debian based systems and
wouldn't actually be used there.
This should not be upstreamed and can be folded into "eos: Add metrics
submission on parental controls blocking run/install" on the next
rebase.
https://phabricator.endlessm.com/T30099
=> eos: Allow metrics to be optional

common/flatpak-dir.c, common/flatpak-transaction.c
This fixes a place where we omit passing a GError pointer and therefore
potentially return FALSE without setting the passed in error. This
causes flatpak_installation_list_installed_refs_for_update() to hit an
assertion failure, crashing libflatpak (and subsequently the App Center
when it's used).
The debug log provided by the user shows messages being printed from
flatpak_dir_prepare_resolve_p2p_refs_helper() for only a subset of the
refs being resolved, and then the log stops since the process crashes,
so that's how I know with near certainty that this patch fixes the
crash experienced by the user on the forum.
The upstream PR on the flatpak-1.6.x branch is here:
https://github.com/flatpak/flatpak/pull/3691
https://phabricator.endlessm.com/T30340
=> dir: Fix an error path with unset GError

common/flatpak-dir.c
Currently Flatpak only supports extensions which come from the same
remote as the thing being extended; for discussion on this see
https://github.com/flatpak/flatpak/issues/861
However in general it isn't clear from the metadata what remote provides
an extension. For example com.endlessm.apps.Platform//5 defines the
extension org.freedesktop.Platform.VAAPI.Intel (inherited from
org.freedesktop.Platform) which can be found on flathub not eos-sdk. So
we don't want to add an extension refspec to the transaction if the
current remote is not the one that actually provides it. In
flatpak_dir_find_remote_related_for_metadata() this invariant is
maintained because we check if the ref exists in the remote before
adding it with add_related(). However in
flatpak_dir_find_local_related_for_metadata() …
=> dir: Fix wrong extension refspecs

sideload-repos-systemd/Makefile.am.inc
Add flatpak-sideload-usb-repo.service.in to EXTRA_DIST regardless of if
the --enable-auto-sideloading configure option was passed. This allows
building a tarball without that option and then building from the
tarball with the option.
This matches what is done in system-helper/Makefile.am.inc with
flatpak-system-helper.service.in.
=> sideload-repos-systemd: Dist service unconditionally

app/flatpak-builtins-enter.c, app/flatpak-builtins-info.c, app/flatpak-builtins-remote-info.c, common/flatpak-dir.c, common/flatpak-transaction.c, common/flatpak-utils.c, portal/flatpak-portal.c, tests/testcommon.c
Backport patches from upstream. This doesn't include the unused runtimes patches (which are pending in https://github.com/flatpak/flatpak/pull/3783) or the summary caching patches (which has ongoing work in https://github.com/flatpak/flatpak/pull/3781).
https://phabricator.endlessm.com/T29642
=> Backport bug fixes from 1.9.x

common/flatpak-utils-http.c
Sometimes a server might return a HTTP error 500 (this seems to happen
sometimes with Microsoft’s VSCode server, for example). Map this to
`G_IO_ERROR_HOST_UNREACHABLE` for now, which is a bit more specific than
returning `G_IO_ERROR_FAILED`, but without the hassle of introducing a
new public error domain which could give more detail.
In particular, this should allow gnome-software to show an error message
to the user for such failed downloads, rather than hiding the error and
logging the following:
```
not handling error failed for action download: While downloading http://packages.microsoft.com/repos/vscode/pool/main/c/code/code_1.45.1-1589445302_amd64.deb: Server returned status 500: Internal Server Error
```
Upstream: https://github.com/flatpak/flatpak/pull/3896
Signed-off-by: Philip …
=> http: Return HOST_UNREACHABLE on error 500

profile/flatpak.sh
If `new_dirs` is empty because the flatpak exported `bin` directories
are already in `PATH`, then `PATH` will contain a trailing `:`. An empty
element in `PATH` means that the current directory should be searched.
While some users may want this behavior, it was not the intention of the
change here to prefix `PATH` with the flatpak exported `bin`
directories. The change here is to only prefix `:` when `new_dirs` is
not empty. This is similar to the `XDG_DATA_DIRS` mangling which only
suffixes `:` if `new_dirs` is not empty.
This can be squashed into dacf0a884ea9d52e763d2f5cb1d720c6fdf7be2f on
the next rebase.
I was surprised to find that programs were being searched for in the current directory and found this to be the culprit. I don't know if the commit title should be in `fixup!` format …
=> profile: Don't add current directory to PATH

common/flatpak-dir-private.h, common/flatpak-dir.c, common/flatpak-transaction.c
This is a trivial backport of https://github.com/flatpak/flatpak/pull/3812 to improve flatpak performance on high-latency networks. There were no cherry pick conflicts.
I would have liked to backport https://github.com/flatpak/flatpak/pull/3781 at the same time, but it’s still awaiting review upstream so hasn’t been included for now.
https://phabricator.endlessm.com/T30404
=> T30404 Backport latency fixes

Makefile.am, configure.ac, env.d/60-flatpak
This is a backport of the commits from https://github.com/flatpak/flatpak/pull/3915 in their state as of today. They haven’t yet been accepted upstream, but it seems like upstream review might take a little while, so I’m pulling these in to EOS now so we can hopefully get them in for 3.9 (once tested on master). They may change upstream before landing and need sorting out when we next rebase.
https://phabricator.endlessm.com/T30972
=> T30972 Backport fix for parental controls in gnome-initial-setup

tests/testlibrary.c
This test test_installation_unused_refs_across_installations() errors
out in the OBS build environment (but passes locally). Disable for now
since this is blocking other tasks. Follow up task is T31027.
https://phabricator.endlessm.com/T22790
=> tests: Skip test using system inst for now

Makefile.am, configure.ac, env.d/60-flatpak
Cherry-pick of #243 to `eos3.9`. No conflicts.
https://phabricator.endlessm.com/T30972
=> T30972 Backport fix for parental controls in gnome-initial-setup (eos3.9)

debian/changelog, debian/flatpak.install
https://phabricator.endlessm.com/T30972
---
Cherry-pick of #245 to `debian-eos3.9`. No conflicts.
=> debian: Install system environment generator (eos3.9)

common/flatpak-dir-private.h, common/flatpak-dir.c, common/flatpak-transaction.c
Trivial cherry-picked backport of #242 to `eos3.9`, so the CI runs.
https://phabricator.endlessm.com/T30404
=> T30404 Backport latency fixes to eos3.9

common/flatpak-installation.c, tests/testlibrary.c
Currently if an app has been renamed and you run "flatpak update" you
will be prompted to decide whether to install the new name of the app
(and uninstall the existing one). However, in such a situation
flatpak_installation_list_installed_refs_for_update() does not return
the app, and therefore gnome-software doesn't see any updates available
(except in the case where the installed commit is older than the commit
with the eol-rebase metadata).
So include end-of-life-rebased apps in the returned list. Patches to
make gnome-software update such apps properly are forthcoming.
I checked that the included unit test only passes with this patch to
libflatpak.
(cherry picked from commit d406cf0ed7cf3d7293d59d281392f3059026f7de)
(There were some minor merge conflicts during cherry-pick, due to the …
=> installation: Include renamed apps when listing updates

common/flatpak-progress.c, common/flatpak-transaction.c, tests/libtest.sh, tests/make-test-app.sh, tests/make-test-runtime.sh, tests/test-auth.sh, tests/test-extensions.sh, tests/test-repo.sh, tests/test-run.sh, tests/test-update-remote-configuration.sh
These are cherry-picks from the upstream 1.8.3 release.
The one "tests: Avoid unnecessarily recreating the summary file" is not strictly necessary since we don't have the latest ostree (which itself hasn't been released) but seems useful in case we update or a developer builds against it.
The changes made to the cherry-picks were minor, and noted in the commit messages.
https://phabricator.endlessm.com/T31110
=> Backports from 1.8.3

common/flatpak-utils.c
There was a bug in the extension point matcher which made it
install `org.gnome.Totem.Videosite.YouTubeDl.Sources` (in addition to
`org.gnome.Totem.Videosite.YouTubeDl`) for the `org.gnome.Totem.Videosite`
extension.
We just need to make sure we only match the extension prefix if there
is a single element in the extension name following the extension
name (i.e. '.YouTubeDl', not '.YouTubeDl.Sources').
This fixes https://github.com/flatpak/flatpak/issues/3973
(cherry picked from commit f650c303e3edff8127ca24fb631b09fcebb36084)
https://phabricator.endlessm.com/T31110
=> Don't auto-install sources for extensions

common/flatpak-dir.c
Currently this error is happening on the eos3.9 dev branch of Endless
OS:
Nov 19 12:05:55 endless eos-updater-flatpak-installer[464]:
eos-updater-flatpak-installer: Couldn’t apply some flatpak update
actions for this boot: Error opening directory
'/root/.local/share/flatpak/app': Permission denied
The reason is that we have a check in flatpak_dir_list_unused_refs() to
check if the per-user installation exists and only try to list the refs
there if so, but the existence check falsely succeeds due to the systemd
sandboxing on eos-updater-flatpak-installer.service, and
flatpak_dir_list_refs() then fails in find_used_refs(). Specifically the
ProtectHome=yes systemd service option makes /root inaccessible, and due
to a bug in GLib[1] this makes g_file_query_exists() falsely return TRUE
for any …
=> dir: Fix spurious permission denied errors

common/flatpak-installation.c
It seems that all `FlatpakTransaction`s add the default dep sources, so
the internal transaction used to list installed refs for updates should
do the same.
This fixes a bug where
`flatpak_installation_list_installed_refs_for_update()` would return an
error saying “The application x requires the runtime y which was not
found” if the app was installed in the user repo, the runtime was
installed in the system repo, and no remote was configured (or one was
configured `xa.noenumerate=true`) in the user repo to provide the
runtime. If a remote was configured, the error wouldn’t be returned, but
the app would be spuriously listed for an update as its runtime couldn’t
be found.
Upstream: https://github.com/flatpak/flatpak/pull/3994 …
=> flatpak-installation: Add default dep sources to list installed refs

common/flatpak-dir.c
Trivial backport of #258 to `eos3.9`.
https://phabricator.endlessm.com/T31249
=> T31249 Backport missing deploy file fix from upstream (eos3.9)

common/flatpak-dir.c
Previously, the polkit query was always interactive, even if the
`FlatpakDir` was operating in non-interactive mode (for example, for a
background update in gnome-software). Make the interactivity match the
interactivity of the `FlatpakDir`.
Do the same for the `mct_manager_get_app_filter()` call, although this
is less important since under normal conditions it will never prompt the
user.
This should hopefully stop polkit prompts appearing periodically when
background updates are being done while logged in as a non-privileged
user with parental controls set to prevent application installation.
---
Trivial backport of https://github.com/flatpak/flatpak/pull/4178
=> flatpak-dir: Make parental controls polkit query interactive iff dir is

tests/web-server.py
On a decently fast system, some files may be fetched, modified and then
fetched again within the same second. In that case, the web server
replies with a code 304 ("Not modified") to the 2nd query, causing some
tests to fail.
This commit forces the web server to ignore `If-Modified-Since` HTTP
headers, effectively disabling caching in order to mitigate the problem.
(cherry picked from commit 6996580bb825b091db9c9bd60cbc5aeff557e7cf)
Currently the flatpak tests are failing in semi-random ways and this fixes the
tests locally for me.
https://phabricator.endlessm.com/T31593
=> tests: web-server: fix an issue with the web server cache

app/flatpak-builtins-create-usb.c
Currently the create-usb command copies extra-data flatpaks such as the
org.freedesktop.Platform.openh264 runtime extension along with normal
non-extra-data content. This is an issue because on the computer
installing from the USB it will attempt to get the extra-data content
from the URI specified in the commit metadata, which will fail if the
URI is a resource on the Internet and the computer is offline.
Instead, have create-usb omit such refs. If it was specified explicitly
this is treated as a hard error and if it's a dependency it's treated as
a warning, so that e.g. org.freedesktop.Platform can still be copied to
a USB and installed/updated offline. On the receiving end the absence of
org.freedesktop.Platform.openh264 will correctly not be treated as fatal
to the installation of …
=> create-usb: Skip copying extra-data flatpaks

system-helper/flatpak-system-helper.c
The system helper was already correctly using the `NO_INTERACTION` flag
in the D-Bus call flags to determine whether polkit calls from
`flatpak_authorize_method_handler()` should allow interactivity.
However, the system helper was not setting the no-interaction property
on the `FlatpakDir` used in the subsequent operation. When parental
controls are enabled, this sometimes results in polkit allowing
interaction when prompting for the `override-parental-controls` action,
even if the D-Bus call which activated the system helper specified the
`NO_INTERACTION` flag.
https://phabricator.endlessm.com/T31351
---
Simple backport of https://github.com/flatpak/flatpak/pull/4199, with some minor conflict resolution done on calls to …
=> system-helper: Set interactivity on the FlatpakDir from D-Bus call flags

app/flatpak-builtins-create-usb.c
This is a eos3.9 backport of #263
https://phabricator.endlessm.com/T31709
=> create-usb: Skip copying extra-data flatpaks (eos3.9 backport)

common/flatpak-transaction.c
If the deploy metadata is missing for the locale runtime of an app which
is being uninstalled, flatpak will currently abort on an assertion
failure.
Prevent that abort, at the expense of not uninstalling the locale
runtime. A better fix could be found for this in future.
Fixes: #3943
Upstream: https://github.com/flatpak/flatpak/pull/4292
https://phabricator.endlessm.com/T32010
=> transaction: Don’t abort on uninstall if deploy metadata is missing

app/flatpak-builtins-build-init.c, app/flatpak-builtins-document-export.c, app/flatpak-builtins-install.c, app/flatpak-builtins-list.c, app/flatpak-builtins-remote-info.c, app/flatpak-builtins-remote-list.c, app/flatpak-builtins-repair.c, app/flatpak-builtins-run.c, app/flatpak-builtins-utils.c, app/flatpak-cli-transaction.c, app/flatpak-table-printer.c, app/flatpak-table-printer.h, common/flatpak-context.c, common/flatpak-dir-private.h, common/flatpak-dir.c, common/flatpak-installation.c, common/flatpak-installation.h, common/flatpak-progress.c, common/flatpak-transaction-private.h, common/flatpak-transaction.c, common/flatpak-utils.c, portal/flatpak-portal.c
The eos-updater unit tests (specifically, the tests which use flatpak) build various test flatpaks and install them using eos-updater-flatpak-installer in various situations. In order to test that there are no assumptions about the architecture in use, all these flatpaks and tests are done for a fictitious `arch` architecture (rather than, say `x86_64`). This used to work fine, but was broken in libflatpak by the transition to the new summary/subsummary architecture.
It was fixed upstream in https://github.com/flatpak/flatpak/issues/4252, but the fix is not in our version of flatpak (1.10.2). This backports it, plus some other fixes from master which look useful (all memory corruption/leak fixes). One of those leak fixes, 756b9eae, is needed to avoid cherry-pick conflicts when backporting …
=> Backport various fixes needed to fix eos-updater unit tests

common/flatpak-transaction.c
Trivial backport of https://github.com/flatpak/flatpak/pull/4316
Need to fix CI for eos-updater.
https://phabricator.endlessm.com/T31918
=> T31918 More flatpak fixes

common/flatpak-dir.c
These checks were broken in commit d762a2f, as the commit failed to
consider the fact that `flatpak_dir_check_parental_controls()` is run
both in the `flatpak` CLI process run by the user, but also in the
`flatpak-system-helper` process which always runs as root, and which
handles any installations done on the system repository.
As a result, parental controls were not working for the system
repository.
Fix that by limiting the scope of the check to only pass if running
without the system helper. flatpak calls from root never go through the
system helper.
Fixes: #4418
https://phabricator.endlessm.com/T32545
=> flatpak-dir: Fix parental controls checks for root

common/flatpak-dir.c
This already happens for installs due to the cleanup path in `flatpak_dir_deploy_install()`, but it doesn’t happen for other calls to `flatpak_dir_deploy()`. Notably, during updates of already installed apps.
Specifically, this means that if an app update is cancelled due to being blocked by a parental controls policy, the temp deploy dir for that app (such as
`~/.local/share/flatpak/app/com.corp.App/x86_64/stable/.somehex-XXXXXX`) will be leaked. It will never be automatically cleaned up, as it’s not in `/var/tmp` either.
Fix that by using `glnx_mkdtempat()` to create a scoped temporary directory.
(cherry picked from commit ce1829a703f2bc2e7868fd314ddefb63fbf7dce1) Upstream: https://github.com/flatpak/flatpak/pull/5158 …
=> flatpak-dir: Clean up temp deploy dir on failure of flatpak_dir_deploy()

common/flatpak-dir.c
This already happens for installs due to the cleanup path in `flatpak_dir_deploy_install()`, but it doesn’t happen for other calls to `flatpak_dir_deploy()`. Notably, during updates of already installed apps.
Specifically, this means that if an app update is cancelled due to being blocked by a parental controls policy, the temp deploy dir for that app (such as
`~/.local/share/flatpak/app/com.corp.App/x86_64/stable/.somehex-XXXXXX`) will be leaked. It will never be automatically cleaned up, as it’s not in `/var/tmp` either.
Fix that by using `glnx_mkdtempat()` to create a scoped temporary directory.
(cherry picked from commit 85a83a06f954080bd1fbba5f07b465955e34040c with minor conflicts)
Upstream: …
=> [eos4.0] flatpak-dir: Clean up temp deploy dir on failure of flatpak_dir_deploy()

common/flatpak-dir.c
This reverts commit 883d9746cac3061b812f494f4ade728ce70e5334. All deployments have been changed to use a standard `bare-user-only` repository instead of a `bare` repository shared with the system OS repo. Now user mode checkouts can always be performed.
https://phabricator.endlessm.com/T34161
=> Revert "Checkout using the same mode of the repo"

common/flatpak-dir.c, tests/test-sideload.sh
This reverts commit 438e8115a46a0cba1d2fc8646d151fc2c7777aba. This has been broken since roughly Flatpak 1.9 and no one noticed because the test gets skipped on our builders.
The only use case for having the `ostree-metadata` commit locally is so that it can be included on a USB that will be consumed by flatpak < 1.7.1. That corresponds to EOS < 3.9. However, even in that case, if the system is online it will check the ref against the remote summary.
So, the `ostree-metadata` commit is only required for a narrow use case of creating a USB for an offline, EOL'd version of Endless. I think dropping it is preferable to trying to add more downstream changes so that it can be fetched again.
https://phabricator.endlessm.com/T34320
=> Revert "Fetch ostree-metadata for backwards compat"

common/flatpak-run.c, doc/flatpak-run.xml
If the `GDK_BACKEND` environment variable is present and it's value does not match the Wayland and X11 socket configuration, then a GTK app will fail to run since it will only consider the display backend from the environment variable.
This should probably be extended to cover other display environment variables such as `QT_QPA_PLATFORM` for Qt and `SDL_VIDEODRIVER` for SDL. However, I've only tested this with GTK applications.
(cherry picked from commit cc122e297235d68301f2c4c466bed997db05937c)
https://phabricator.endlessm.com/T34456
=> flatpak-run: Unset GDK_BACKEND

debian/rules
Our fontconfig package has been changed to generate the system font cache in `/usr/lib/fontconfig/cache` so that it can be shipped in the OS commit. By default, flatpak considers that only if `/var/cache/fontconfig` doesn't exist. Normally that's the case, but some systems may have a stray directory that prevents using system fonts in applications. Change the setting so that only the system cache in `/usr` is considered.
https://phabricator.endlessm.com/T34305
=> Only load fontconfig cache from /usr/lib/fontconfig/cache

debian/rules
Our fontconfig package has been changed to generate the system font cache in `/usr/lib/fontconfig/cache` so that it can be shipped in the OS commit. By default, flatpak considers that only if `/var/cache/fontconfig` doesn't exist. Normally that's the case, but some systems may have a stray directory that prevents using system fonts in applications. Change the setting so that only the system cache in `/usr` is considered.
https://phabricator.endlessm.com/T34305
(cherry picked from commit d008894ab656a152facf8804ac78dc8cb8596a0a)
=> Backport "Only load fontconfig cache from /usr/lib/fontconfig/cache" to eos4.0

common/flatpak-transaction.c, tests/test-repo.sh, tests/testlibrary.c
If `no_deploy` has been set to `TRUE` in a transaction, then the intention is that no changes will be made to the installed flatpaks. Currently that's not the case for explicitly or implicitly added uninstall operations. That's particularly bad for eol-rebase flatpaks since they old version will be automatically removed without the new version being installed. To address this, prevent uninstall operations from being added for no deploy transactions.
Closes: #5172
https://phabricator.endlessm.com/T34071
This is taken from flatpak/flatpak#5289. It's almost a clean cherry pick of the one commit, but there have been some minor changes in `tests/test-repo.sh` that caused some conflicts.
=> transaction: Ignore uninstall operations for no deploy

common/flatpak-transaction.c, tests/test-repo.sh, tests/testlibrary.c
If `no_deploy` has been set to `TRUE` in a transaction, then the intention is that no changes will be made to the installed flatpaks. Currently that's not the case for explicitly or implicitly added uninstall operations. That's particularly bad for eol-rebase flatpaks since they old version will be automatically removed without the new version being installed. To address this, prevent uninstall operations from being added for no deploy transactions.
Closes: #5172
https://phabricator.endlessm.com/T34071
(cherry picked from commit 7ecfa0b64aace11c7e81e47063e0876657e54e72)
The changes picked cleanly except for a minor conflict in some surrounding code. I haven't actually tested it but it works properly on master.
=> Backport "transaction: Ignore uninstall operations for no deploy" to eos4.0

debian/changelog
Debian is now backporting 1.14 to bullseye, so there was no upstream packaging to include. There were also no actual packaging changes, so it's just the new changelog entry.
https://phabricator.endlessm.com/T34619
=> 1.12.8 Debian packaging
