endlessm/flatpak

common/flatpak-utils.c
https://phabricator.endlessm.com/T13735
=> flatpak-utils: accommodate old search provider names

system-helper/org.freedesktop.Flatpak.rules.in
https://phabricator.endlessm.com/T14239
=> system-helper: Do not ask for password when removing apps/runtimes

app/flatpak-builtins-build-finish.c
https://phabricator.endlessm.com/T14478
=> build-finish: Export MIME Types

debian/control
https://phabricator.endlessm.com/T14872
=> Remove bzr Recommends

common/flatpak-run.c
https://phabricator.endlessm.com/T15102
=> Added support for Mali drivers to --device=dri

common/flatpak-dir.c, common/flatpak-utils.c, lib/flatpak-installation.c
https://phabricator.endlessm.com/T15083
=> Fix progress reporting when installing external apps via the public API

app/flatpak-builtins-build-finish.c
https://phabricator.endlessm.com/T16446
=> build-finish: Add Endless Grand Central Content Providers

app/flatpak-builtins-build-finish.c
https://phabricator.endlessm.com/T16446
=> builtins: Rename location of Discovery Feed content providers

common/flatpak-dir.c
=> dir: make sure to whitelist our additional exports

common/flatpak-dir.c
When any of the pull or deploy processes during a flatpak install
hits a ENOSPC situation, the created temporary files at
~/.local/share/flatpak/system-cache were not deleted leaving
the disk full.
https://phabricator.endlessm.com/T15391
=> Remove cache directory when install runs out of disk

app/flatpak-builtins-add-remote.c
Updating the metadata at the end of adding a remote means that it fails
if we're offline, even if we have the .flatpakrepo file available.
Unlike the other error cases in the process, which mean the operation
really has messed up, the remote is actually usable even if the
metadata update fails, because future operations will grab the
summary and any new metadata - so we should change this to a warning
to allow the operation to succeed when we're offline.
https://github.com/flatpak/flatpak/issues/917
For Endless, this should fix our repo adds appearing to fail when the
network isn't available at boot time.
https://phabricator.endlessm.com/T17172
=> allow remote add to succeed when offline

common/flatpak-run.c
This apps rely on having access to the `XDG_DOCUMENTS_DIR` directory from inside the sandbox, which should already be the case considering they have `host` filesystem access. Unfortunately, a recent commit in flatpak [1] broke this in cases where the `~/.var/app/com.endlessm.resume/config/user-dirs.dirs` was not previously created, meaning that all new installations of these apps won't work at all.
Fortunately, cherry picking this fix from upstream will solve the issue, by no longer requiring the `~/.var/app/com.endlessm.resume/config/user-dirs.dirs` to exist before creating the bind mount with bwrap, thus making the XDG_DOCUMENTS_DIR variable (and other xdg-* ones) visible again. 
[1] https://github.com/flatpak/flatpak/commit/f1df5cb1
https://phabricator.endlessm.com/T20458
=> Fix the broken Resume and Finance apps

common/flatpak-dir.c, system-helper/flatpak-system-helper.c
Fix a crash and a potential crash from https://phabricator.endlessm.com/T20789.
Both patches upstream at:
* https://github.com/flatpak/flatpak/commit/35aef1fa2cd65e6c8c4906c2011cf3582179bcd6
* https://github.com/flatpak/flatpak/pull/1320
=> T20789 progress crash

common/flatpak-run.c, dbus-proxy/flatpak-proxy.c
https://phabricator.endlessm.com/T21005
=> T21005 Backport security fixes from 0.10.3 release

.gitignore, app/flatpak-builtins-build-bundle.c, app/flatpak-transaction.c, common/flatpak-dir.c, common/flatpak-dir.h, common/flatpak-utils.c, completion/flatpak, doc/flatpak-remote-ls.xml, lib/flatpak-installation.c, tests/Makefile.am.inc, tests/test-build-update-repo.sh
These are cherry picks of upstream commits: the three needed for T21399 and others that seem uncontroversial and not risky.
https://phabricator.endlessm.com/T21399
=> Upstream cherry picks

doc/reference/flatpak-sections.txt, lib/flatpak-installation.c, lib/flatpak-installation.h
This will be consumed by eos-updater for now, but could be interesting for upstream too.
https://phabricator.endlessm.com/T22621
=> Allow requesting "no prune" updates/uninstalls via the public API

common/flatpak-dir.c
In upstream OSTree, the default for core.add-remotes-config-dir is true
for system repositories and false for all other repositories. Since we
use the same repository for the OS and for flatpak, we need the
configuration value to be the same for both (otherwise there can be
conflicts between /etc/flatpak/remotes.d/*.conf and
/ostree/repo/config).
While we set core.add-remotes-config-dir=false in all our configurations
for OSTree, this patch exists for paranoia, as the consequences of using
the wrong default value for it are hard to recover from (essentially, a
non-updatable system).
This patch will set core.add-remotes-config-dir=false in the OSTree
config when a FlatpakDir is initialised, if that config key has not
already been set explicitly. So in the case that …
=> common/dir: Change default of core.add-remotes-config-dir to false

common/flatpak-run.c
https://phabricator.endlessm.com/T23852
=> run: Expose previous-ids symlinks into sandbox

app/flatpak-builtins-create-usb.c
Change the create-usb command so that it always creates the destination
repository using the "archive" mode, rather than using archive mode when
xattrs aren't supported and bare-user otherwise. This has a few
advantages:
1. The archive mode works with FAT filesystems, which is what most USB
drives are, and which doesn't support xattrs. This should fix
https://github.com/flatpak/flatpak/issues/2019 but it would be good to
confirm.
2. At least in some quick testing I did, archive mode is about twice as
performant as bare-user mode, in terms of how long it takes for the
create-usb command to complete.
3. This ensures that a tool can safely change the permissions on
".ostree/repo" and subdirectories after create-usb completes, which is
important for Endless since otherwise you can't use …
=> create-usb: Always use archive mode

common/flatpak-run.c
https://phabricator.endlessm.com/T23852
=> fixup! run: Expose previous-ids symlinks into sandbox

debian/libflatpak0.symbols
Add flatpak_installation_get_min_free_space_bytes to symbols file
https://phabricator.endlessm.com/T23694
=> Update symbols file

common/flatpak-transaction.c
Unmodified cherry pick of upstream patch for https://phabricator.endlessm.com/T24058
=> common: Reload FlatpakRemoteState after changes

common/flatpak-run.c
https://phabricator.endlessm.com/T24302
=> T24302 Ignore parental controls for nonexistent users

common/Makefile.am.inc, common/flatpak-dir-private.h, common/flatpak-dir.c, common/flatpak-parental-controls-private.h, common/flatpak-parental-controls.c, system-helper/Makefile.am.inc, system-helper/flatpak-system-helper.c, system-helper/org.freedesktop.Flatpak.rules.in
https://phabricator.endlessm.com/T24457
=> T24457 polkit all the things

common/flatpak-dir.c
@ramcq didn't like the old string.
https://phabricator.endlessm.com/T24024
=> dir: improve error when an app's content is too extreme

common/flatpak-run.c
https://phabricator.endlessm.com/T25146
=> flatpak-run: mark parental controls message for translation

debian/changelog, debian/control
https://phabricator.endlessm.com/T25194
=> Depend on libeos-parental-controls-0-dev and release 1.1.3-2endless2

app/flatpak-builtins-build-commit-from.c, app/flatpak-builtins-build-export.c, app/flatpak-cli-transaction.c, app/flatpak-main.c, common/flatpak-dir.c, common/flatpak-run.c, common/flatpak-utils-private.h, common/flatpak-utils.c, doc/flatpak-build-commit-from.xml, icon-validator/validate-icon.c, system-helper/flatpak-system-helper.c, tests/make-test-app.sh, tests/make-test-runtime.sh
https://phabricator.endlessm.com/T25194
=> Fix compiler warnings/errors and unit tests

app/flatpak-builtins-build-commit-from.c, app/flatpak-builtins-build-init.c, app/flatpak-cli-transaction.c, app/flatpak-main.c, common/flatpak-appdata.c, common/flatpak-dir-private.h, common/flatpak-dir.c, common/flatpak-installation.c, common/flatpak-utils.c, icon-validator/validate-icon.c, profile/flatpak.sh, tests/testcommon.c, tests/testlibrary.c
These are cherry-picks of upstream commits which seem important and not risky.
https://phabricator.endlessm.com/T25361
=> Backports from 1.2.2

app/flatpak-builtins-build-bundle.c, app/flatpak-builtins-build-commit-from.c, app/flatpak-builtins-build-export.c, app/flatpak-builtins-build-sign.c, app/flatpak-builtins-repo.c, common/flatpak-dir.c, common/flatpak-installation.c, common/flatpak-utils-private.h, common/flatpak-utils.c, tests/Makefile-test-matrix.am.inc, tests/Makefile.am.inc, tests/libtest.sh, tests/make-test-app.sh, tests/make-test-runtime.sh, tests/test-p2p-security.sh
These are clean cherry-picks from upstream except for some minor conflicts in these two commits:
- dir: Fix an edge case of resolving collection-refs
- Made wider use of flatpak_repo_resolve_rev()
https://phabricator.endlessm.com/T25084
=> T25084 Use the correct keyring for P2P pulls

app/flatpak-builtins-remote-info.c, common/flatpak-dir.c, common/flatpak-error.h, common/flatpak-installation.c, common/flatpak-utils.c
https://phabricator.endlessm.com/T26678
=> T26678 Add FLATPAK_ERROR_REF_NOT_FOUND

.gitignore, .tx/config, po/cs.po, po/da.po, po/de.po, po/es.po, po/flatpak.pot, po/gl.po, po/hu.po, po/id.po, po/pl.po, po/pt_BR.po, po/ru.po, po/sk.po, po/sv.po, po/tr.po, po/uk.po, po/zh_TW.po
https://phabricator.endlessm.com/T25388
=> Re-enable and update translations

profile/flatpak.sh
Use syntax compatible with OpenBSD ksh; see
https://github.com/flatpak/flatpak/pull/2947
https://phabricator.endlessm.com/T27001
=> fixup! profile/flatpak.sh: add export/bin dirs to PATH

common/flatpak-run.c
This seems to work fine although I am not sure if that is the best way to get the desktop file/mimetypes there, please check and let me know if you have other suggestions.
Tested with:
```
andrunko@endless:~$ sudo malcontent-client set 1001 x-scheme-handler/http
App filter for user 1001 set
andrunko@endless:~$ DISPLAY=:0 /usr/bin/flatpak run --branch=stable --arch=x86_64 --command=eolie --file-forwarding org.gnome.Eolie http://google.com
error: Running app/org.gnome.Eolie/x86_64/stable is not allowed by the policy set by your administrator
```
After resetting the filter I can run `Eolie` again. Also running other apps that don't handle `x-scheme-handler/http` works as expected with and without the filter set.
https://phabricator.endlessm.com/T27009
=> flatpak-run: Also filter by content type on parental controls checks

system-helper/org.freedesktop.Flatpak.rules.in
Check for app-installation permissions for all users (including
admins).
https://phabricator.endlessm.com/T26968
=> system-helper: Apply Parental Controls to privileged users

app/flatpak-cli-transaction.c, common/flatpak-transaction.c
Fixes for some small issues found while testing.
=> Small fixes

common/flatpak-installation.c
This prevents a crash in flatpak_installation_list_remotes_by_type() if
the `FlatpakDir` can’t ensure it has a repo configured.
https://phabricator.endlessm.com/T27337
---
WIP: I am still testing this
=> flatpak-installation: Handle an unconfigured remote when listing remotes

common/flatpak-installation.c
Upstream: https://github.com/flatpak/flatpak/pull/3031
=> installation: Fix a small leak of a FlatpakCollectionRef

app/flatpak-builtins-build-bundle.c, common/flatpak-dir.c, common/flatpak-utils.c, tests/test-bundle.sh
These are cherry-picks from upstream that applied cleanly.
https://phabricator.endlessm.com/T27248
=> T27248 Fix build-bundle command

app/flatpak-builtins-build-init.c, common/flatpak-dir.c, common/flatpak-transaction.c, configure.ac, doc/flatpak-metadata.xml
https://phabricator.endlessm.com/T27865
=> Backport changes to allow extensions to use extra-data (and lie about the version)

common/flatpak-dir.c
https://phabricator.endlessm.com/T27854
=> Fix some flatpak regressions

common/flatpak-dir.c, common/flatpak-parental-controls.c, system-helper/org.freedesktop.Flatpak.policy.in, system-helper/org.freedesktop.Flatpak.rules.in
https://phabricator.endlessm.com/T27854
=> Fix more regressions

po/cs.po, po/da.po, po/de.po, po/en_GB.po, po/es.po, po/flatpak.pot, po/gl.po, po/hu.po, po/id.po, po/pl.po, po/pt_BR.po, po/ru.po, po/sk.po, po/sv.po, po/tr.po, po/uk.po, po/zh_TW.po
https://phabricator.endlessm.com/T28002
=> Reapply downstream translations

common/flatpak-dir-private.h, common/flatpak-dir.c, common/flatpak-installation.c, tests/testlibrary.c
(Subset) Backport of https://github.com/flatpak/flatpak/pull/3204
https://phabricator.endlessm.com/T28302
=> installation: Return main app as updatable if related extensions are missing

common/flatpak-dir.c
Cherry-picks from upstream
https://phabricator.endlessm.com/T29125
=> T29125 fix g-s crash

common/flatpak-installation.c, common/flatpak-transaction.c, common/flatpak-transaction.h, common/flatpak-utils-private.h
Trivial backport of:
* https://github.com/flatpak/flatpak/pull/3568
* https://github.com/flatpak/flatpak/pull/3580
https://phabricator.endlessm.com/T29774
=> T29774 Backport APIs needed for g-s progress bar improvements

common/flatpak-dir-private.h, common/flatpak-dir.c, common/flatpak-transaction.c, doc/flatpak-flatpakref.xml, doc/flatpak-remote-add.xml, doc/flatpak-remote-modify.xml, doc/flatpak-remote.xml, tests/testlibrary.c
This is a backport of https://github.com/flatpak/flatpak/pull/3751 so the unit tests pass in https://github.com/endlessm/eos-updater/pull/272
https://phabricator.endlessm.com/T23150
=> Backport runtime remote priority change

debian/flatpak.install
https://phabricator.endlessm.com/T30368
=> debian/flatpak.install: Update for systemd changes

sideload-repos-systemd/flatpak-create-sideload-symlinks.sh, sideload-repos-systemd/flatpak-sideload-usb-repo.path.in, sideload-repos-systemd/flatpak-sideload-usb-repo.service.in
Backports from https://github.com/flatpak/flatpak/pull/3866
https://phabricator.endlessm.com/T30368
=> Backport sideload fixes

debian/changelog, debian/flatpak.install
https://phabricator.endlessm.com/T30972
=> debian: Install system environment generator

common/flatpak-dir-private.h, common/flatpak-dir.c, common/flatpak-transaction.c, common/flatpak-utils.c
https://phabricator.endlessm.com/T31162
=> Ensure deploy files have complete metadata

.github/workflows/check.yml, common/flatpak-bwrap-private.h, common/flatpak-bwrap.c, common/flatpak-context.c, common/flatpak-run.c, common/flatpak-utils-base-private.h, doc/flatpak-build-finish.xml, doc/flatpak-build.xml, doc/flatpak-override.xml, doc/flatpak-run.xml, portal/flatpak-portal.c, tests/Makefile.am.inc, tests/libpreload.c, tests/test-override.sh
https://phabricator.endlessm.com/T31239
=> Backports from 1.8.4 and 1.8.5

common/flatpak-dir.c
See https://github.com/flatpak/flatpak/pull/4085
https://phabricator.endlessm.com/T31249
=> Backport missing deploy file fix from upstream
